spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://172.177.184.144:3306/okplay_dev
    username: okplay_dev
    password: 23XrFDE6pN6c5PwH
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  key:
    private: classpath:rsa.private.key
    public: classpath:rsa.public.key

springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html
    operations-sorter: method

