spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://localhost:3306/sogogo-engine
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  key:
    private: classpath:rsa.private.key
    public: classpath:rsa.public.key

springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html
    operations-sorter: method

